/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatLaf;

/**
 *
 * @author muham
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        namaField.putClientProperty("JTextField.placeholderText","Nama sesuai KTP");
        nohpField.putClientProperty("JTextField.placeholderText","08xxxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        nohpLabel = new javax.swing.JLabel();
        kotatujuanLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        fasilitasLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        nohpField = new javax.swing.JTextField();
        kotaCombo = new javax.swing.JComboBox<>();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanText = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Tiket Travel");

        namaLabel.setText("Nama Pemesan");

        nohpLabel.setText("Nomor HP");

        kotatujuanLabel.setText("Kota Tujuan");

        kelasLabel.setText("Kelas");

        fasilitasLabel.setText("Fasilitas Tambahan");

        catatanLabel.setText("Catatan");

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasGroup.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        kelasGroup.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");

        kelasGroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        catatanText.setColumns(20);
        catatanText.setRows(3);
        jScrollPane1.setViewportView(catatanText);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fasilitasLabel)
                    .addComponent(kelasLabel)
                    .addComponent(kotatujuanLabel)
                    .addComponent(nohpLabel)
                    .addComponent(namaLabel)
                    .addComponent(catatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaField)
                    .addComponent(nohpField)
                    .addComponent(kotaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesanButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ekonomiRadio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bisnisRadio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eksekutifRadio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bagasiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(makanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(asuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nohpLabel)
                    .addComponent(nohpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotatujuanLabel)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasLabel)
                    .addComponent(ekonomiRadio)
                    .addComponent(bisnisRadio)
                    .addComponent(eksekutifRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fasilitasLabel)
                    .addComponent(bagasiCheck)
                    .addComponent(makanCheck)
                    .addComponent(asuransiCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catatanLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanButton)
                    .addComponent(temaToggle))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    private void tampilkanRingkasan() {
    String kelas = ekonomiRadio.isSelected() ? "Ekonomi"
            : bisnisRadio.isSelected() ? "Bisnis"
            : "Eksekutif";

    List<String> fasilitas = new ArrayList<>();

    for (JCheckBox cb : List.of(bagasiCheck, makanCheck, asuransiCheck)) {
        if (cb.isSelected()) {
            fasilitas.add(cb.getText());
        }
    }

    String pesan = "Nama Pemesan: " + namaField.getText()
            + "\nNomor HP: " + nohpField.getText()
            + "\nKota Tujuan: " + kotaCombo.getSelectedItem()
            + "\nKelas: " + kelas
            + "\nFasilitas: " + (fasilitas.isEmpty()
                    ? "-" : String.join(", ", fasilitas))
            + "\nCatatan: " + catatanText.getText();

    JOptionPane.showMessageDialog(
            this,
            pesan,
            "Ringkasan Pemesanan",
            JOptionPane.INFORMATION_MESSAGE
    );
    }
    
    private void gantiTema(boolean gelap) {
    if (gelap) {
        FlatDarkLaf.setup();
    } else {
        FlatLightLaf.setup();
    }

    FlatLaf.updateUI();
    temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextArea catatanText;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasGroup;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JLabel kotatujuanLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nohpField;
    private javax.swing.JLabel nohpLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
